name: build



on:
  push:
      tags:
      - 'v*'

  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and Test
        run: |
           chmod +x gradlew
           ./gradlew shadowJar
           ls -R
           
      - uses: actions/upload-artifact@v1
        with:
          name: chef-helper
          path: build/libs
          
      - name: Release with Assets 
        uses: UVASOMIT/action-release-with-assets@master
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           commitish: dev
           files: 'build/libs'
           prerelease: false
           body: This is a release
           name: Draft Release
           tag: v1     
